version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: maets-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: maets-mongo
    environment:
      MONGO_INITDB_DATABASE: maets
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo/data:/data/db

  app:
    build: .
    container_name: maets-app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MONGO_URI=mongodb://mongo:27017/maets
      - HTTPS=true
      - HTTPS_PORT=3443
      - SSL_KEY_PATH=/app/certs/key.pem
      - SSL_CERT_PATH=/app/certs/cert.pem
    ports:
      - "3000:3000"
      - "3443:3443"
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgres
      - mongo

volumes:
  postgres-data:
